name: Skip docker status checks

on:
  workflow_call:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - run: 'echo "No docker build required"'
